### ISSUE TITLE
git-ready-to-deploy.sh is not a .PHONY target in Makefile

### ISSUE THREAD

**Issue by diegolgz** [oleks/git-ready-to-deploy#1]
According to [`make` documentation](https://www.gnu.org/software/make/manual/html_node/Phony-Targets.html), real file names shouldn't be .PHONY targets.

**Comment by oleks** [comment]
Do you mean (1) that it isn't,or (2) that it shouldn't?

If (1), In which version of `make` is `git-ready-to-deploy.sh` not considered a phony target? For instance, it is in my GNU Make 4.2.1.

If (2), I agree. The reason it is though, is that it is a crude solution to make sure `git-ready-to-deploy.sh` is rebuilt every time a change is committed to git, since a git tag is written to `git-ready-to-deploy.sh`. A much better solution would be to update `git-ready-to-deploy.sh` only if `.git/HEAD`, or the file referred to by `.git/HEAD` has changed. Would you agree?

**Comment by diegolgz** [comment]
It shouldn't. In make 4.1 a target with a real file name shouldn't be a .PHONY target, but if you write it as .PHONY target it will work well.

If (2), I agree with that better solution. `git-ready-to-deploy.sh` target could depend on `.git/HEAD` file (I think it is not necessary to depend on the file referred by `.git/HEAD`).

**Comment by oleks** [comment]
Closed by #2
